on:
  push:
    branches:
      - main
      

jobs:
  build:
    runs-on: Ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: "Building image"
        run: docker build -t 20486903/image .
        
      - name: "Login"
        run: docker login --username ${{secrets.TokenUsername}} --password ${{secrets.TokenPassword}}
              
      - name: ""
        run: 
